
name: AMAR WORKFLOW

on:
  

  workflow_dispatch:
    inputs:
      ValueA:
        description: 'First Name'
        required: true
        default: '--'
        
        

      ValueB:
        description: 'Last Name'
        required: true
        default: '--'

env:
  a: ${{github.event.inputs.ValueA}}
  b: ${{github.event.inputs.ValueB}}       
        

  
jobs:
  run-python-test:
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
  
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
  
      - name: Execute Test Script
        run:  python3 scripts/test.py $a $b


      
      
      
            
   
    